language: node_js
node_js:
  - "6"
  - "7"
  - "8"
install:
  - npm i -g npm
  - npm install
  - npm install coveralls
script:
  - npm test
notifications:
  email:
    on_failure: change
jobs:
  include:
    - stage: lint
      node_js: "8"
      script:
        - npm run lint
    - stage: coverage
      node_js: "8"
      script:
        - npm run test -- --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
